### ISSUE TITLE
Register user

### ISSUE THREAD

**Issue by MurhafSousli** [EyeSeeTea/FIRE-MockServer#12]
Hi @tokland  👋

I am getting this error when I try to register a new user

![image](https://user-images.githubusercontent.com/8130692/28504949-6a228bc6-7027-11e7-937a-021762cc3d56.png)

```
export interface RegisterForm {
  name: string;
  surname: string;
  password: string;
  email: string;
  phoneNumber: string;
  address: string;
  gender: string;
}

this.fireHttp.post('/newUserRequests', form);
```

**Comment by adrianq** [comment]
I guess you meant @tokland

**Comment by tokland** [comment]
@MurhafSousli Did you enclose the user info? `{"user": {"username": ..., ....}}`

https://github.com/EyeSeeTea/FIRE-MockServer#newuserrequest
https://github.com/EyeSeeTea/FIRE-MockServer/blob/master/fire.py#L92
https://github.com/EyeSeeTea/FIRE-MockServer/blob/master/test_fire.py#L81

**Comment by MurhafSousli** [comment]
@tokland Ok, now it's works

**Comment by tokland** [comment]
@MurhafSousli Cool!
