### ISSUE TITLE
New user request parameters?

### ISSUE THREAD

**Issue by MurhafSousli** [EyeSeeTea/FIRE-MockServer#13]
I am wondering about the required parameters for creating a new user request _(I might have missed understood something, so please correct me if I am wrong!)_

Looking at **NewUserRequest** in **Models**, I don't see a need to get the created/updated dates from the client side. Why do we get the dates from user's phone, what if his time is incorrect!

In fact, the server would only need the user's form in order to create the new user.

Current **NewUserRequest** Model
```
id: Int
user: User
created: Date
updated: Date
adminUser: User
state: String ("pending" | "accepted" | "rejected")
```

Instead the app will only send the form
```
user: User
```
And the server will take care of the rest
```
created: Date
updated: Date
adminUser: User | adminId: number
state: String ("pending" | "accepted" | "rejected")
```

**Comment by tokland** [comment]
Those attributes (dates/state/...) are internal of the model, so you are right, the post is sending just _User_. (any other field is ignored) See: https://github.com/EyeSeeTea/FIRE-MockServer/blob/master/test_fire.py#L81

I'll edit the README to make more clear that you just send the user field.

Note that I wrote the mock server quickly and yet without a full understanding of the app, propose as many things as you see fit!
