### ISSUE TITLE
Multiple selection requests

### ISSUE THREAD

**Issue by MurhafSousli** [EyeSeeTea/FIRE-MockServer#14]
In case the Admin has selected multiple users from the users list to send a message to a group of users

With the current implementation, the client app will need to start a loop of requests against the server to send each message to each user.

Assume the admin is sending this message to 100 users, means 100 requests.

Wouldn't it be better if the server can accept multiple users ids `[102, 111, 112, ...]` in the request parameter and then it loops over them to send the message. this way the action will be done in 1 request instead of a 100 requests. 

---

### 1 request per user

**Pros**:
  - Allows instant reporting for each operation `Sending: 48/200  progress 24%`
  - Allows cancellation

**Cons**:
 - Too many requests
 - Can take a long time to finish
 - Can be interrupted

---

### 1 request for all

**Pros**:
 - Allows final report from the server `Message was sent to 113 users`.
 - Much faster approach, can send 100 users in a very short time.

**Comment by tokland** [comment]
I'll change the endpoint so you can send a message to N users.
