### ISSUE TITLE
Add admin field to login

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/FIRE-MockServer#18]

**Comment by adrianq** [comment]
@MurhafSousli this was done. Documentation was wrong but we do have an admin field. I have just updated the docs. Can you please take care of https://github.com/EyeSeeTea/FIRE-WiFiCalling/issues/14 as it could be fully done now? Thanks!

**Comment by MurhafSousli** [comment]
@adrianq It is done but it is in feature/settings, is it okay to keep it there or should I open a new PR for Polish Menu?

**Comment by adrianq** [comment]
I think I answered your question here https://github.com/EyeSeeTea/FIRE-WiFiCalling/issues/14#issuecomment-323527941 but let me know if I have misunderstood your question. Thanks!

**Comment by MurhafSousli** [comment]
I got it :+1: Thanks
